import './globals.css';
import { Inter } from 'next/font/google';
import NavbStyle from './components/NavbStyle';
import TopNav from './components/TopNav';
import FooterStyle from './components/FooterStyle';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className=''>
        <TopNav />
        <NavbStyle />
        {children}
        <FooterStyle />
      </body>
    </html>
  );
}
